"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  AlertTriangle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CloudUpload,
  Database,
  Download,
  FileText,
  MoreVertical,
  Search,
  ShieldCheck,
  Trash2,
  X,
} from "lucide-react";
import { DropdownSelect } from "../ui/dropdown-select";

export type BackupType = "Full" | "Incremental";
export type BackupStatus = "Success" | "Running" | "Failed";

export type BackupRecord = {
  id: string;
  backupId: string;
  name: string;
  type: BackupType;
  dateLabel: string;
  dateValue: string;
  createdBy: string;
  size: string;
  status: BackupStatus;
  statusDetail?: string;
  storageName: string;
  storageRegion: string;
  checksum: string;
  duration: string;
  includedItems: string;
  notes: string;
};

const PAGE_SIZE = 8;
const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const dateFilterOptions = [
  { value: "7", label: "Last 7 days" },
  { value: "30", label: "Last 30 days" },
];

export const typeFilterOptions = [
  { value: "Full", label: "Full" },
  { value: "Incremental", label: "Incremental" },
];

export const statusFilterOptions = [
  { value: "Success", label: "Success" },
  { value: "Failed", label: "Failed" },
  { value: "Running", label: "Running" },
];

function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function pad(value: number, length = 2) {
  return String(value).padStart(length, "0");
}

function formatBackupDate(date: Date, hour = 2, minute = 0) {
  const period = hour >= 12 ? "PM" : "AM";
  const hour12 = hour % 12 || 12;
  return `${MONTHS[date.getUTCMonth()]} ${date.getUTCDate()}, ${date.getUTCFullYear()} ${pad(hour12)}:${pad(minute)} ${period}`;
}

export function typeBadge(type: BackupType) {
  return type === "Full"
    ? "bg-violet-50 text-violet-600"
    : "bg-blue-50 text-[var(--color-active-menu)]";
}

function statusTone(status: BackupStatus) {
  if (status === "Failed") return "text-red-600";
  if (status === "Running") return "text-amber-600";
  return "text-[var(--color-success)]";
}

function statusDot(status: BackupStatus) {
  if (status === "Failed") return "bg-red-500";
  if (status === "Running") return "bg-amber-500";
  return "bg-[var(--color-success)]";
}

export function createInitialBackups(): BackupRecord[] {
  const records: BackupRecord[] = [];
  const start = new Date(Date.UTC(2026, 4, 13));

  for (let index = 0; index < 48; index += 1) {
    const date = new Date(start);
    date.setUTCDate(start.getUTCDate() - index);
    const year = date.getUTCFullYear();
    const month = pad(date.getUTCMonth() + 1);
    const day = pad(date.getUTCDate());
    const isFull = index % 2 === 0;
    const failed = index === 5;
    const fullSize = (2.45 - Math.floor(index / 2) * 0.02).toFixed(2);
    const incrementalSize = index === 1 ? "420.12 MB" : `${186 + ((index * 17) % 80)} MB`;
    const durationMinutes = isFull ? 4 : 1;
    const durationSeconds = isFull ? 12 - (index % 8) : 8 + (index % 12);

    records.push({
      id: `bk-${pad(index + 1, 3)}`,
      backupId: `bkp_${year}${month}${day}_020000_${isFull ? "full" : "incr"}`,
      name: isFull ? "Daily Backup" : "Incremental Backup",
      type: isFull ? "Full" : "Incremental",
      dateLabel: formatBackupDate(date),
      dateValue: `${year}-${month}-${day}T02:00:00.000Z`,
      createdBy: "System",
      size: isFull ? `${fullSize} GB` : incrementalSize,
      status: failed ? "Failed" : "Success",
      statusDetail: failed ? "Upload failed" : undefined,
      storageName: "Supabase Storage",
      storageRegion: "Singapore (southeast-1)",
      checksum: `a1b2c3d4e5f${pad(index, 3)}…9a0b1c2d3e4f`,
      duration: `00:${pad(durationMinutes)}:${pad(Math.max(durationSeconds, 0))}`,
      includedItems: "Database, Files, Configurations",
      notes: "Automatically generated by system",
    });
  }

  return records;
}

export function createManualBackup(): BackupRecord {
  return {
    id: `bk-${Date.now()}`,
    backupId: "bkp_20260513_021800_full",
    name: "Manual Backup",
    type: "Full",
    dateLabel: "May 13, 2026 02:18 AM",
    dateValue: "2026-05-13T02:18:00.000Z",
    createdBy: "Admin User",
    size: "2.46 GB",
    status: "Success",
    storageName: "Supabase Storage",
    storageRegion: "Singapore (southeast-1)",
    checksum: "c9d8e7f6a5b4…1a2b3c4d5e6f",
    duration: "00:03:58",
    includedItems: "Database, Files, Configurations",
    notes: "Started manually from Backup & Recovery",
  };
}

export function BackupStatusLabel({ backup }: { backup: BackupRecord }) {
  return (
    <span className={cx("inline-flex flex-col", statusTone(backup.status))}>
      <span className="inline-flex items-center gap-1.5 text-sm font-semibold">
        <span className={cx("h-1.5 w-1.5 rounded-full", statusDot(backup.status))} />
        {backup.status}
      </span>
      {backup.statusDetail ? (
        <span className="mt-0.5 pl-3 text-xs font-medium text-red-500">{backup.statusDetail}</span>
      ) : null}
    </span>
  );
}

export function BackupNameCell({ backup }: { backup: BackupRecord }) {
  const failed = backup.status === "Failed";
  const NameIcon = failed ? AlertTriangle : backup.type === "Full" ? Database : FileText;

  return (
    <div className="flex items-center gap-3">
      <span
        className={cx(
          "flex h-9 w-9 shrink-0 items-center justify-center rounded-xl",
          failed
            ? "bg-red-50 text-red-500"
            : backup.type === "Full"
              ? "bg-emerald-50 text-[var(--color-success)]"
              : "bg-blue-50 text-[var(--color-active-menu)]",
        )}
      >
        <NameIcon className="h-4 w-4" />
      </span>
      <span>
        <span className="block font-semibold text-slate-900">{backup.name}</span>
        <span className="mt-0.5 block text-xs text-slate-400">
          {backup.type === "Full" ? "Full Backup" : "Incremental Backup"}
        </span>
      </span>
    </div>
  );
}

export function backupPageNumbers(current: number, total: number): Array<number | "ellipsis"> {
  if (total <= 6) {
    return Array.from({ length: total }, (_, index) => index + 1);
  }
  if (current <= 3) return [1, 2, 3, "ellipsis", total];
  if (current >= total - 2) return [1, "ellipsis", total - 2, total - 1, total];
  return [1, "ellipsis", current, "ellipsis", total];
}

function DetailRow({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex items-start justify-between gap-4 py-2.5">
      <dt className="text-sm text-slate-500">{label}</dt>
      <dd className="max-w-[60%] text-right text-sm font-semibold text-slate-800">{children}</dd>
    </div>
  );
}

export default function BackupHistoryPanel({
  backups,
  onChangeBackups,
  onRunBackupNow,
  isRunningBackup,
  onBanner,
}: {
  backups: BackupRecord[];
  onChangeBackups: (updater: (current: BackupRecord[]) => BackupRecord[]) => void;
  onRunBackupNow: () => void;
  isRunningBackup: boolean;
  onBanner: (message: string) => void;
}) {
  const [search, setSearch] = useState("");
  const [dateFilter, setDateFilter] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [page, setPage] = useState(1);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [menuId, setMenuId] = useState<string | null>(null);

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    const newest = backups[0] ? new Date(backups[0].dateValue) : new Date("2026-05-13T02:00:00.000Z");

    return backups.filter((backup) => {
      if (query) {
        const haystack = `${backup.name} ${backup.backupId} ${backup.type} ${backup.createdBy}`.toLowerCase();
        if (!haystack.includes(query)) return false;
      }
      if (typeFilter && backup.type !== typeFilter) return false;
      if (statusFilter && backup.status !== statusFilter) return false;
      if (dateFilter) {
        const cutoff = new Date(newest);
        cutoff.setUTCDate(cutoff.getUTCDate() - Number(dateFilter));
        if (new Date(backup.dateValue) < cutoff) return false;
      }
      return true;
    });
  }, [backups, dateFilter, search, statusFilter, typeFilter]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const currentPage = Math.min(page, totalPages);
  const pageStart = filtered.length === 0 ? 0 : (currentPage - 1) * PAGE_SIZE;
  const pageItems = filtered.slice(pageStart, pageStart + PAGE_SIZE);
  const pageEnd = pageStart + pageItems.length;
  const selected = backups.find((backup) => backup.id === selectedId) ?? null;

  useEffect(() => {
    setPage(1);
  }, [dateFilter, search, statusFilter, typeFilter]);

  function verifyBackup(backup: BackupRecord) {
    if (backup.status === "Failed") {
      onBanner(`Verification failed for ${backup.name}. ${backup.statusDetail ?? "Backup is not usable."}`);
      return;
    }
    onBanner(`${backup.name} verified. Checksum matches.`);
  }

  function deleteBackup(backup: BackupRecord) {
    onChangeBackups((current) => current.filter((item) => item.id !== backup.id));
    if (selectedId === backup.id) setSelectedId(null);
    setMenuId(null);
    onBanner(`${backup.name} deleted. This is a mockup and no files were removed.`);
  }

  return (
    <>
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex min-w-0 flex-1 flex-col gap-2 sm:flex-row sm:items-center">
          <label className="flex h-11 min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-slate-400 sm:max-w-sm">
            <Search className="h-4 w-4 shrink-0" />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search backups..."
              className="min-w-0 flex-1 border-0 bg-transparent text-sm text-slate-800 outline-none"
            />
          </label>
          <div className="grid grid-cols-3 gap-2 sm:flex sm:w-auto">
            <DropdownSelect
              value={dateFilter}
              onChange={(value) => setDateFilter(value)}
              options={dateFilterOptions}
              placeholder="All Dates"
              allowClear
              size="sm"
              className="min-w-[8.5rem]"
              aria-label="Filter by date"
            />
            <DropdownSelect
              value={typeFilter}
              onChange={(value) => setTypeFilter(value)}
              options={typeFilterOptions}
              placeholder="All Types"
              allowClear
              size="sm"
              className="min-w-[8.5rem]"
              aria-label="Filter by type"
            />
            <DropdownSelect
              value={statusFilter}
              onChange={(value) => setStatusFilter(value)}
              options={statusFilterOptions}
              placeholder="All Status"
              allowClear
              size="sm"
              className="min-w-[8.5rem]"
              aria-label="Filter by status"
            />
          </div>
        </div>
        <div className="flex flex-col gap-2 sm:flex-row">
          <button
            type="button"
            onClick={() => {
              const target = selected ?? pageItems[0];
              if (!target) {
                onBanner("Select a backup to verify.");
                return;
              }
              verifyBackup(target);
            }}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[var(--color-active-menu)] bg-white px-4 text-sm font-semibold text-[var(--color-active-menu)]"
          >
            <ShieldCheck className="h-4 w-4" />
            Verify Backup
          </button>
          <button
            type="button"
            onClick={onRunBackupNow}
            disabled={isRunningBackup}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[var(--color-active-menu)] px-4 text-sm font-semibold text-white disabled:opacity-60"
          >
            <CloudUpload className="h-4 w-4" />
            {isRunningBackup ? "Running..." : "Run Backup Now"}
          </button>
        </div>
      </div>

      <section className="overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,0.04)]">
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs font-bold uppercase tracking-[0.08em] text-slate-400">
                <th className="px-4 py-3">Backup Name</th>
                <th className="px-4 py-3">Type</th>
                <th className="px-4 py-3">
                  <span className="inline-flex items-center gap-1">
                    Date & Time
                    <ChevronDown className="h-3.5 w-3.5" />
                  </span>
                </th>
                <th className="px-4 py-3">Size</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Storage Location</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {pageItems.map((backup) => (
                <tr
                  key={backup.id}
                  onClick={() => {
                    setSelectedId(backup.id);
                    setMenuId(null);
                  }}
                  className={cx(
                    "cursor-pointer border-b border-slate-100 last:border-0 transition",
                    selectedId === backup.id ? "bg-blue-50/70" : "hover:bg-slate-50",
                  )}
                >
                  <td className="px-4 py-3.5">
                    <BackupNameCell backup={backup} />
                  </td>
                  <td className="px-4 py-3.5">
                    <span
                      className={cx(
                        "inline-flex rounded-full px-2.5 py-1 text-xs font-bold",
                        typeBadge(backup.type),
                      )}
                    >
                      {backup.type}
                    </span>
                  </td>
                  <td className="px-4 py-3.5 text-slate-600">
                    <div>{backup.dateLabel}</div>
                    <div className="text-xs text-slate-400">by {backup.createdBy}</div>
                  </td>
                  <td className="px-4 py-3.5 font-semibold text-slate-700">{backup.size}</td>
                  <td className="px-4 py-3.5">
                    <BackupStatusLabel backup={backup} />
                  </td>
                  <td className="px-4 py-3.5">
                    <div className="font-semibold text-slate-800">{backup.storageName}</div>
                    <div className="text-xs text-slate-400">{backup.storageRegion}</div>
                  </td>
                  <td className="px-4 py-3.5">
                    <div className="relative flex items-center justify-end gap-1">
                      <button
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation();
                          onBanner(`Download started for ${backup.name}. This is a mockup.`);
                        }}
                        className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-white hover:text-slate-700"
                        aria-label={`Download ${backup.name}`}
                      >
                        <Download className="h-4 w-4" />
                      </button>
                      <button
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation();
                          setMenuId((current) => (current === backup.id ? null : backup.id));
                        }}
                        className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-white hover:text-slate-700"
                        aria-label={`More actions for ${backup.name}`}
                      >
                        <MoreVertical className="h-4 w-4" />
                      </button>
                      {menuId === backup.id ? (
                        <div className="absolute right-0 top-9 z-20 w-44 overflow-hidden rounded-xl border border-slate-200 bg-white py-1 shadow-[0_18px_40px_rgba(15,23,42,0.14)]">
                          <button
                            type="button"
                            onClick={(event) => {
                              event.stopPropagation();
                              setSelectedId(backup.id);
                              setMenuId(null);
                            }}
                            className="flex w-full px-3 py-2 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"
                          >
                            View details
                          </button>
                          <button
                            type="button"
                            onClick={(event) => {
                              event.stopPropagation();
                              setMenuId(null);
                              verifyBackup(backup);
                            }}
                            className="flex w-full px-3 py-2 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"
                          >
                            Verify backup
                          </button>
                          <button
                            type="button"
                            onClick={(event) => {
                              event.stopPropagation();
                              deleteBackup(backup);
                            }}
                            className="flex w-full px-3 py-2 text-left text-sm font-semibold text-red-600 hover:bg-red-50"
                          >
                            Delete backup
                          </button>
                        </div>
                      ) : null}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filtered.length === 0 ? (
          <div className="px-5 py-12 text-center text-sm text-slate-500">
            No backups match the current search or filters.
          </div>
        ) : (
          <div className="flex flex-col gap-3 border-t border-slate-200 px-4 py-3.5 sm:flex-row sm:items-center sm:justify-between">
            <div className="text-sm text-slate-500">
              Showing {pageStart + (pageItems.length ? 1 : 0)} to {pageEnd} of {filtered.length} backups
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setPage((current) => Math.max(1, current - 1))}
                disabled={currentPage <= 1}
                className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"
                aria-label="Previous page"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
              {backupPageNumbers(currentPage, totalPages).map((item, index) =>
                item === "ellipsis" ? (
                  <span key={`ellipsis-${index}`} className="px-1 text-sm font-semibold text-slate-400">
                    …
                  </span>
                ) : (
                  <button
                    key={item}
                    type="button"
                    onClick={() => setPage(item)}
                    className={cx(
                      "inline-flex h-9 min-w-9 items-center justify-center rounded-lg border px-2.5 text-sm font-semibold transition",
                      item === currentPage
                        ? "border-[var(--color-active-menu)] bg-white text-[var(--color-active-menu)] shadow-[0_0_0_1px_var(--color-active-menu)]"
                        : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:bg-slate-50",
                    )}
                    aria-current={item === currentPage ? "page" : undefined}
                  >
                    {item}
                  </button>
                ),
              )}
              <button
                type="button"
                onClick={() => setPage((current) => Math.min(totalPages, current + 1))}
                disabled={currentPage >= totalPages}
                className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"
                aria-label="Next page"
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        )}
      </section>

      {selected ? (
        <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={() => setSelectedId(null)}>
          <aside
            className="flex h-full w-full max-w-md flex-col bg-white shadow-[-18px_0_40px_rgba(15,23,42,0.12)]"
            onClick={(event) => event.stopPropagation()}
          >
            <div className="flex items-start justify-between gap-3 border-b border-slate-200 px-5 py-4">
              <div className="flex items-center gap-3">
                <span
                  className={cx(
                    "flex h-10 w-10 items-center justify-center rounded-xl",
                    selected.status === "Failed"
                      ? "bg-red-50 text-red-500"
                      : "bg-emerald-50 text-[var(--color-success)]",
                  )}
                >
                  {selected.status === "Failed" ? (
                    <AlertTriangle className="h-5 w-5" />
                  ) : (
                    <Database className="h-5 w-5" />
                  )}
                </span>
                <div>
                  <h3 className="text-base font-bold text-slate-900">Backup Details</h3>
                  <p className="text-xs text-slate-400">{selected.backupId}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setSelectedId(null)}
                className="rounded-lg p-1 text-slate-400 transition hover:bg-slate-50 hover:text-slate-700"
                aria-label="Close details"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto px-5 py-5">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="text-lg font-bold text-slate-900">{selected.name}</div>
                  <div className="mt-1 text-sm text-slate-500">
                    {selected.type === "Full" ? "Full Backup" : "Incremental Backup"}
                  </div>
                </div>
                <span
                  className={cx(
                    "inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold",
                    selected.status === "Failed"
                      ? "bg-red-50 text-red-600"
                      : "bg-emerald-50 text-[var(--color-success)]",
                  )}
                >
                  <span className={cx("h-1.5 w-1.5 rounded-full", statusDot(selected.status))} />
                  {selected.status}
                </span>
              </div>

              <dl className="mt-5 divide-y divide-slate-100 border-y border-slate-100">
                <DetailRow label="Backup Name">{selected.name}</DetailRow>
                <DetailRow label="Backup Type">{selected.type}</DetailRow>
                <DetailRow label="Date & Time">
                  {selected.dateLabel}
                  <span className="mt-0.5 block text-xs font-medium text-slate-400">
                    (UTC+08:00) Asia/Manila
                  </span>
                </DetailRow>
                <DetailRow label="Size">{selected.size}</DetailRow>
                <DetailRow label="Status">
                  <BackupStatusLabel backup={selected} />
                </DetailRow>
                <DetailRow label="Storage Location">
                  {selected.storageName}
                  <span className="mt-0.5 block text-xs font-medium text-slate-400">
                    {selected.storageRegion}
                  </span>
                </DetailRow>
                <DetailRow label="Backup ID">
                  <span className="break-all font-mono text-xs">{selected.backupId}</span>
                </DetailRow>
                <DetailRow label="Checksum (SHA256)">
                  <span className="break-all font-mono text-xs">{selected.checksum}</span>
                </DetailRow>
                <DetailRow label="Duration">{selected.duration}</DetailRow>
                <DetailRow label="Included Items">{selected.includedItems}</DetailRow>
                <DetailRow label="Notes">{selected.notes}</DetailRow>
              </dl>
            </div>

            <div className="grid gap-2 border-t border-slate-200 p-5 sm:grid-cols-3">
              <button
                type="button"
                onClick={() => onBanner(`Download started for ${selected.name}. This is a mockup.`)}
                className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"
              >
                <Download className="h-4 w-4" />
                Download
              </button>
              <button
                type="button"
                onClick={() => verifyBackup(selected)}
                className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-[var(--color-active-menu)] bg-white px-3 text-sm font-semibold text-[var(--color-active-menu)]"
              >
                <ShieldCheck className="h-4 w-4" />
                Verify Backup
              </button>
              <button
                type="button"
                onClick={() => deleteBackup(selected)}
                className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-red-200 bg-white px-3 text-sm font-semibold text-red-600"
              >
                <Trash2 className="h-4 w-4" />
                Delete Backup
              </button>
            </div>
          </aside>
        </div>
      ) : null}
    </>
  );
}
