"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Eye,
  Printer,
  Search,
  Trash2,
} from "lucide-react";
import { DropdownSelect } from "../ui/dropdown-select";
import {
  formatDateRange,
  formatReportDateTime,
  parseDateInput,
  type ReportFormat,
  type ReportHistoryItem,
  type ReportHistoryStatus,
} from "./reports-data";

const formatOptions = [
  { value: "View", label: "Viewed" },
  { value: "CSV", label: "CSV" },
  { value: "XLS", label: "XLS" },
  { value: "PDF", label: "PDF" },
];
const statusOptions = [
  { value: "Completed", label: "Completed" },
  { value: "Failed", label: "Failed" },
];
const pageSizeOptions = [
  { value: "10", label: "10" },
  { value: "25", label: "25" },
];

function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function pageNumbers(current: number, total: number): Array<number | "ellipsis"> {
  if (total <= 7) return Array.from({ length: total }, (_, index) => index + 1);
  if (current <= 4) return [1, 2, 3, 4, 5, "ellipsis", total];
  if (current >= total - 3) return [1, "ellipsis", total - 4, total - 3, total - 2, total - 1, total];
  return [1, "ellipsis", current - 1, current, current + 1, "ellipsis", total];
}

export function ReportsHistory({
  items,
  onView,
  onExportCsv,
  onExportPdf,
  onDelete,
}: {
  items: ReportHistoryItem[];
  onView: (item: ReportHistoryItem) => void;
  onExportCsv: (item: ReportHistoryItem) => void;
  onExportPdf: (item: ReportHistoryItem) => void;
  onDelete: (item: ReportHistoryItem) => void;
}) {
  const [search, setSearch] = useState("");
  const [formatFilter, setFormatFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState("10");

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    return items.filter((item) => {
      if (query) {
        const haystack = `${item.name} ${item.generatedBy} ${item.format}`.toLowerCase();
        if (!haystack.includes(query)) return false;
      }
      if (formatFilter && item.format !== formatFilter) return false;
      if (statusFilter && item.status !== statusFilter) return false;
      return true;
    });
  }, [formatFilter, items, search, statusFilter]);

  const size = Number(pageSize) || 10;
  const totalPages = Math.max(1, Math.ceil(filtered.length / size));
  const currentPage = Math.min(page, totalPages);
  const pageStart = filtered.length === 0 ? 0 : (currentPage - 1) * size;
  const pageItems = filtered.slice(pageStart, pageStart + size);
  const pageEnd = pageStart + pageItems.length;

  useEffect(() => {
    setPage(1);
  }, [search, formatFilter, statusFilter, pageSize]);

  return (
    <section className="overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,0.04)]">
      <div className="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 lg:flex-row lg:items-center">
        <label className="flex h-10 min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-slate-400">
          <Search className="h-4 w-4 shrink-0" />
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search generated reports..."
            className="min-w-0 flex-1 border-0 bg-transparent text-sm text-slate-800 outline-none"
          />
        </label>
        <div className="flex flex-wrap gap-2">
          <DropdownSelect
            value={formatFilter}
            onChange={(value) => setFormatFilter(value)}
            options={formatOptions}
            placeholder="All Formats"
            allowClear
            size="sm"
            className="min-w-[9rem]"
            aria-label="Filter by format"
          />
          <DropdownSelect
            value={statusFilter}
            onChange={(value) => setStatusFilter(value)}
            options={statusOptions}
            placeholder="All Statuses"
            allowClear
            size="sm"
            className="min-w-[9rem]"
            aria-label="Filter by status"
          />
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full text-left text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-xs font-bold uppercase tracking-[0.08em] text-slate-400">
              <th className="px-5 py-3">Report Name</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3">Date Generated</th>
              <th className="px-4 py-3">Date Range</th>
              <th className="px-4 py-3">Format</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3" />
            </tr>
          </thead>
          <tbody>
            {pageItems.map((item) => (
              <tr key={item.id} className="border-b border-slate-100 last:border-0">
                <td className="px-5 py-3.5">
                  <button
                    type="button"
                    onClick={() => onView(item)}
                    className="text-left font-bold text-[var(--color-active-menu)] hover:underline"
                  >
                    {item.name}
                  </button>
                  <div className="mt-0.5 text-xs text-slate-400">{item.rowCount} rows</div>
                </td>
                <td className="px-4 py-3.5 font-medium text-slate-700">{item.generatedBy}</td>
                <td className="whitespace-nowrap px-4 py-3.5 text-slate-600">
                  {formatReportDateTime(new Date(item.generatedAt))}
                </td>
                <td className="whitespace-nowrap px-4 py-3.5 text-slate-600">
                  {formatDateRange(parseDateInput(item.dateFrom), parseDateInput(item.dateTo))}
                </td>
                <td className="px-4 py-3.5">
                  <FormatBadge format={item.format} />
                </td>
                <td className="px-4 py-3.5">
                  <StatusBadge status={item.status} />
                </td>
                <td className="px-4 py-3.5">
                  <div className="flex items-center justify-end gap-1">
                    <button
                      type="button"
                      onClick={() => onView(item)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-50 hover:text-slate-700"
                      aria-label={`View ${item.name}`}
                    >
                      <Eye className="h-4 w-4" />
                    </button>
                    <button
                      type="button"
                      onClick={() => onExportCsv(item)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-50 hover:text-slate-700"
                      aria-label={`Export ${item.name} as CSV`}
                    >
                      <Download className="h-4 w-4" />
                    </button>
                    <button
                      type="button"
                      onClick={() => onExportPdf(item)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-50 hover:text-slate-700"
                      aria-label={`Export ${item.name} as PDF`}
                    >
                      <Printer className="h-4 w-4" />
                    </button>
                    <button
                      type="button"
                      onClick={() => onDelete(item)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 hover:bg-red-50 hover:text-red-600"
                      aria-label={`Delete ${item.name} from history`}
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {pageItems.length === 0 ? (
              <tr>
                <td colSpan={7} className="px-5 py-10 text-center text-sm text-slate-500">
                  {items.length === 0
                    ? "No reports have been generated yet."
                    : "No generated reports match the current search or filters."}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col gap-3 border-t border-slate-200 px-5 py-3.5 lg:flex-row lg:items-center lg:justify-between">
        <div className="text-sm text-slate-500">
          Showing {pageStart + (pageItems.length ? 1 : 0)} to {pageEnd} of {filtered.length} generated reports
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <label className="inline-flex items-center gap-2 text-sm text-slate-500">
            Rows per page:
            <DropdownSelect
              value={pageSize}
              onChange={(value) => setPageSize(value || "10")}
              options={pageSizeOptions}
              size="sm"
              className="w-[4.5rem]"
              aria-label="Rows per page"
            />
          </label>
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              onClick={() => setPage((current) => Math.max(1, current - 1))}
              disabled={currentPage <= 1}
              className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 disabled:opacity-40"
              aria-label="Previous page"
            >
              <ChevronLeft className="h-4 w-4" />
            </button>
            {pageNumbers(currentPage, totalPages).map((item, index) =>
              item === "ellipsis" ? (
                <span key={`ellipsis-${index}`} className="px-1 text-sm font-semibold text-slate-400">
                  …
                </span>
              ) : (
                <button
                  key={item}
                  type="button"
                  onClick={() => setPage(item)}
                  className={cx(
                    "inline-flex h-9 min-w-9 items-center justify-center rounded-lg border px-2.5 text-sm font-semibold",
                    item === currentPage
                      ? "border-[var(--color-active-menu)] bg-white text-[var(--color-active-menu)] shadow-[0_0_0_1px_var(--color-active-menu)]"
                      : "border-slate-200 bg-white text-slate-600",
                  )}
                >
                  {item}
                </button>
              ),
            )}
            <button
              type="button"
              onClick={() => setPage((current) => Math.min(totalPages, current + 1))}
              disabled={currentPage >= totalPages}
              className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 disabled:opacity-40"
              aria-label="Next page"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}

function FormatBadge({ format }: { format: ReportFormat }) {
  const label = format === "View" ? "Viewed" : format;
  return (
    <span
      className={cx(
        "inline-flex rounded-full px-2.5 py-1 text-xs font-bold",
        format === "PDF"
          ? "bg-violet-50 text-violet-600"
          : format === "CSV"
            ? "bg-emerald-50 text-emerald-700"
            : format === "XLS"
              ? "bg-teal-50 text-teal-700"
              : "bg-blue-50 text-[var(--color-active-menu)]",
      )}
    >
      {label}
    </span>
  );
}

function StatusBadge({ status }: { status: ReportHistoryStatus }) {
  return (
    <span className="inline-flex items-center gap-1.5 text-sm font-semibold">
      <span className={cx("h-1.5 w-1.5 rounded-full", status === "Failed" ? "bg-red-500" : "bg-[var(--color-success)]")} />
      <span className={status === "Failed" ? "text-red-600" : "text-[var(--color-success)]"}>{status}</span>
    </span>
  );
}
